name: Dash
version: '2.0'
main: dash.Dash
api-version: '1.21'
author: Frxme
description: Server admin dashboard with web interface
commands:
  dash:
    description: Dash admin commands
    usage: '/dash register [user] [rank] | /dash update'
    permission: dash.register
permissions:
  dash.register:
    description: Allows generating web registration codes
    default: op
